traiterJson({
"trait":2,
"numDiag":1,
"notes": "nn",
"fen": "uDTtuB2 r",
"bonusJ":-1,
"malusJ":-1,
"bonusR":-1,
"malusR":4,
"cols":[ 
	{"nb":1, "couleur":2},
	{"nb":2, "couleur":1},
	{"nb":3, "couleur":1},
	{"nb":3, "couleur":2},
	{"nb":2, "couleur":2},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0}
]
});
