traiterJson({
"trait":2,
"numDiag":1,
"notes": "Pas de note spécifier",
"fen": "tdtUDU42 r",
"bonusJ":0,
"malusJ":0,
"bonusR":0,
"malusR":0,
{"nb":, "couleur"0},
{"nb":, "couleur"0},
{"nb":, "couleur"0},
{"nb":, "couleur"0},
{"nb":, "couleur"0},
{"nb":, "couleur"0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
{"nb":0, "couleur":0},
]
 });
