traiterJson({
"trait":2,
"numDiag":1,
"notes": "mlp 
pok
",
"fen": "uB2 r",
"bonusJ":-1,
"malusJ":-1,
"bonusR":-1,
"malusR":0,
"cols":[ 
	{"nb":2, "couleur":2},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0}
]
});
